### ISSUE TITLE
add this package to MELPA

### ISSUE THREAD

**Issue by stardiviner** [pinguim06/pdf-tools-org#3]
Here is my recipe PR:
https://github.com/melpa/melpa/pull/4368

I create PR to `pdf-tools-org` with some requirements for MELPA.

**Comment by machc** [comment]
Hey, thanks for doing this! I'll gladly merge your PR with the MELPA requirements when it's ready.

**Comment by stardiviner** [comment]
@machc hi, I created my PR now. thanks for this.
