### ISSUE TITLE
Error on annotation export: Invalid tag specification

### ISSUE THREAD

**Issue by wildgruber** [pinguim06/pdf-tools-org#7]
My setup is: 
emacs version: GNU Emacs 27.0.50
Org mode version 9.1.14
pdf-tools-org newest git checkout
pdf-tools from melpa: 20180428.1527

When I tried to export annotations from a pdf I get this error:
`Invalid tag specification: 1`

This is caused by the `org-set-tags 1` function in the `pdf-tools-org-export-to-org` function in  pdf-tools-org.el. If I omit this line, it works and the resulting org file actually has tags. But what might be the problem?

Any help on this?

Thanks

**Comment by Ypot** [comment]
Same problem here. I can't export my highlights.
